version: '3.8'
name: todo_app
services:
  api:
    build:
      context: ./Todo_app
      dockerfile: Dockerfile
    volumes:
      - ./Todo_app:/code  # Sync local development directory with the container
    depends_on:
        - Todo_db
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000
  Todo_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: todo_app_container
    environment:
        - POSTGRES_USER=hasaanqureshi
        - POSTGRES_PASSWORD=my-todo9513
        - POSTGRES_DB=my-todo-app
    ports:
        - '5433:5432'
    volumes:
        - Todo_db:/var/lib/postgresql/data
  cloudflared:
    image: cloudflare/cloudflared:latest
    environment:
      TUNNEL_URL: http://api:8000
    command: "tunnel --no-autoupdate"
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - api
volumes:
  Todo_db:
    driver: local
networks:
  default:
    driver: bridge